= README.adoc for CaelyfDoctor Project


== Status

*Travis C/I* Project Health -
image:https://img.shields.io/travis/jnorthr/CaelyfDoctor.svg[Build Status (Travis CI), link=https://travis-ci.org/jnorthr/CaelyfDoctor]

''''

This project is used as a base-line to test DoctorTemplateEngine and it's documentation.

Gretty is used to test using localhost:8080 fro browser address bar. These sample pages belonging to GPars - a different project but only used here as a sample. See routes.groovy for full navigation within the site.

As a secondary task, since caelyf-1.3.3.jar is used, this version of Caelyf allows the DoctorTemplateEngine to be used when testing CaelyfServlets or GroovyTemplateServlets

This Engine is invoked in the web.xml file where a new TemplateServlet called DoctorTemplateServet is declared and connected to any file ending with .adoc, .ad, .asciidoc. etc. 

When any request arrives pointing to an .adoc file, the text from that file is passed to the DoctorTemplateEngine. This template engine uses the asciidoctorJ module to convert that text composed in asciidoctor syntax into an .html page for onward/return use by the originating browser.

Several asciidoctor dependencies are declared in the build.gradle script file. These are typically :

.Gradle Dependencies
----
dependencies {
    compile "org.codehaus.groovy:groovy-all:2.4.5" // supports programming

    runtime "org.jruby:jruby-complete:1.7.21"	// needed for asciidoctorJ
    runtime "com.beust:jcommander:1.48"		// needed for asciidoctorJ
    runtime "org.asciidoctor:asciidoctorj:1.5.3.2" // needed for DoctorTemplateEngine
    runtime "redis.clients:jedis:2.7.2" // runtime failure in Caelyf if not included
}
----

