get "/",      	    forward: "WEB-INF/pages/index.adoc"
get "/ad",      	forward: "WEB-INF/pages/test.adoc"
get "/readme",      forward: "WEB-INF/pages/README.adoc"
get "/test", 		forward: "/test.groovy"
get "/formdata", 	forward: "/formdata.groovy"
get "/render",      forward: "WEB-INF/pages/render.gtpl"
get "/datetime", 	forward: "/datetime.groovy"
